version: "3"
services:
  calculate-rewards:
    image: calculate-rewards
    ports:
      - "8080:8080"
    networks:
      - calculate-rewards-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - calculate-rewards-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb  

networks:
  calculate-rewards-mysql: